---
title: "Mini #02 - Identifying Environmentally Responsible US Public Transit Systems"
---

## Introduction

Among the commonly cited benefits of robust public transit is a reduction in environmental impact. In this mini-project, we will explore US Public Transit systems to assess their environmental efficiency. Our analysis will use a variety of data sources to:

1.  Determine how many riders are served by different transit systems.
2.  Determine how far each public transit system transports an average rider.
3.  Investigate the effective emissions associated with each form of transit.

## Data Acquisition

For this mini-project, we will download the following details:

-   EIA State Electricity Profiles: Used to estimate the environmental impact of the electricity used to run certain transit systems.

## Task 1: Importing EIA State Electricity Profiles Data

For purposes of this analysis, we assume that all electricity generation in a state is fungible. That is, we assign the average generation emissions to all electric transit in a state, even if the transit authority officially has a "green supply" agreement in place.

The following code will parse the EIA SEP summary pages and create a "tidy" table for analysis:

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org"))

library(dplyr)
library(stringr)
library(rvest)
library(httr2)
library(purrr)
library(scales)
library(DT)

get_eia_sep <- function(state, abbr){
    state_formatted <- str_to_lower(state) %>% str_replace_all("\\s", "")

    dir_name <- file.path("data", "mp02")
    file_name <- file.path(dir_name, state_formatted)
    
    dir.create(dir_name, showWarnings=FALSE, recursive=TRUE)
    
    if (!file.exists(file_name)) {
        BASE_URL <- "https://www.eia.gov"
        REQUEST <- request(BASE_URL) %>% 
            req_url_path("electricity", "state", state_formatted) %>% 
            req_headers("User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)")
    
        RESPONSE <- req_perform(REQUEST)
    
        resp_check_status(RESPONSE)
        
        writeLines(resp_body_string(RESPONSE), file_name)
    }

    message("Checking file: ", file_name)  

    if (!file.exists(file_name)) {
        message("File not found after request for ", state)
        return(NULL)
    }

    TABLE_RAW <- read_html(file_name) %>% html_element("table")

    if (is.null(TABLE_RAW)) {
        message("No table found for ", state)
        return(NULL)
    }

    TABLE <- TABLE_RAW %>% 
        html_table() %>% 
        mutate(Item = str_to_lower(Item))

    if("U.S. rank" %in% colnames(TABLE)){
        TABLE <- TABLE %>% rename(Rank = `U.S. rank`)
    }
    
    CO2_MWh <- TABLE %>% 
        filter(Item == "carbon dioxide (lbs/mwh)") %>%
        pull(Value) %>% 
        str_replace_all(",", "") %>%
        as.numeric()
    
    PRIMARY <- TABLE %>% 
        filter(Item == "primary energy source") %>% 
        pull(Rank)
    
    RATE <- TABLE %>%
        filter(Item == "average retail price (cents/kwh)") %>%
        pull(Value) %>%
        as.numeric()
    
    GENERATION_MWh <- TABLE %>%
        filter(Item == "net generation (megawatthours)") %>%
        pull(Value) %>%
        str_replace_all(",", "") %>%
        as.numeric()
    
    data.frame(CO2_MWh               = CO2_MWh, 
               primary_source        = PRIMARY,
               electricity_price_MWh = RATE * 10, 
               generation_MWh        = GENERATION_MWh, 
               state                 = state, 
               abbreviation          = abbr
    )
}

EIA_SEP_REPORT <- map2(state.name, state.abb, get_eia_sep) %>% 
                  purrr::compact() %>% 
                  dplyr::bind_rows()


EIA_SEP_REPORT <- EIA_SEP_REPORT %>% 
    mutate(electricity_price_MWh = dollar(electricity_price_MWh, accuracy = 0.01))

DT::datatable(EIA_SEP_REPORT) %>%
  formatStyle(
    "CO2_MWh",  # Align CO2_MWh to left
    `text-align` = "left"
  ) %>%
  formatStyle(
    "generation_MWh",  # Align generation_MWh to left
    `text-align` = "left"
  ) 
```
## Task 2:  Initial Analysis of SEP Data 

Which state has the most expensive retail electricity?

